In [1]:
from sample_psrs import load_psrs, fake_model_2a, fake_model_2a_no_tm
from pta_fast_model import FastLogLikelihood
from enterprise.signals.signal_base import FastLogLikelihood as FastLikelihood

import numpy as np

from enterprise.signals import utils
from enterprise_extensions.models import model_2a
%load_ext autoreload
%autoreload 2

Loading fastloglikelihood version of signal_base
Do not have mpi4py package.


In [2]:
psrs = load_psrs(1e-15, 1)

In [3]:
pta = fake_model_2a_no_tm([psrs[0]])

In [21]:
like = FastLogLikelihood(pta, [psrs[0]])

In [20]:
like([2, -15, -15])

66904.64689615586

In [3]:
pta_fast = fake_model_2a([psrs[1]], slow=False)
pta_slow = fake_model_2a([psrs[1]], slow=True)

Loading fastloglikelihood version of signal_base


In [16]:
pta_fast = fake_model_2a([psrs[0]], slow=False)

In [4]:
def diff(x):
    return np.abs(pta_fast.get_lnlikelihood(x) - pta_slow.get_lnlikelihood(x)) / pta_slow.get_lnlikelihood(x)

In [8]:
for ii in range(1000):
    x0 = np.random.uniform(0, 7)
    x1 = np.random.uniform(-20, -11)
    x2 = np.random.uniform(-20, -12)
    res = diff([x0, x1, x2])
    if res > 1e-7:
        print([x0, x1, x2])
        print(res)

[1.2831491288410164, -18.575036772639674, -17.385607592869725]
4.33419907633631e-07
[0.6379772474272941, -15.853215742962538, -17.473271294639357]
1.256470370517258e-07
[1.5579627050438993, -16.550628153477813, -17.394487502885983]
1.5054021606197207e-07
[2.7436707347811464, -16.573648569414, -18.299339491081376]
1.7559562633891554e-07
[4.376784801166585, -17.39862891729012, -17.925925696638423]
1.0864530940373595e-07


In [13]:
x = [0.6379772474272941, -15.853215742962538, -17.473271294639357]
print(pta_slow.get_lnlikelihood(x))
print(pta_fast.get_lnlikelihood(x))

x = [1.2831491288410164, -18.575036772639674, -17.385607592869725]
print(pta_slow.get_lnlikelihood(x))
print(pta_fast.get_lnlikelihood(x))

2687.112237733323
2687.1119001056322
421.8386313216761
421.83844848841545


In [39]:
x = [3.5435624061278403, -11.150845217554435, -13.704689462496248]
print(pta_fast.get_lnlikelihood(x))
print(pta_slow.get_lnlikelihood(x))

Loading fastloglikelihood version of signal_base
66769.62610796285
2098.953064078649
5203.200269882498
9593.744884552092
66769.62610784461


In [63]:
time_span = np.max(psrs[0].toas) - np.min(psrs[0].toas)
print(time_span)

347069251.21145725


In [49]:
pta_fast.get_lnlikelihood([0, 0, -20, -20, -20])

344300627725.8132
186610279.4675873


51036.67147527121

In [23]:
pta_slow.get_lnlikelihood([2, -15, -15])

17896069273883.61


66904.64689615493

In [26]:
pta0._signalcollections[1].get_phi([0, -20, -20]).shape

(241,)

In [14]:
np.linalg.cond(psrs[1].Mmat)
np.linalg.cond(utils.normed_tm_basis(psrs[1].Mmat)[0])

142965.33466048178

In [64]:
utils.normed_tm_basis(psrs[0].Mmat)

(array([[ 0.01334164, -0.00607742, -0.01744352, ...,  0.        ,
          0.        , -0.01498558],
        [ 0.01334164, -0.00607742, -0.01744352, ...,  0.        ,
          0.        , -0.01498558],
        [ 0.01334164, -0.00607742, -0.01744352, ...,  0.        ,
          0.        , -0.01498558],
        ...,
        [ 0.01334164, -0.00633331, -0.01738768, ...,  0.        ,
          0.24175482,  0.        ],
        [ 0.01334164, -0.00633331, -0.01738768, ...,  0.        ,
          0.24519369,  0.        ],
        [ 0.01334164, -0.00633331, -0.01738768, ...,  0.        ,
          0.24346461,  0.        ]]),
 array(1))

In [82]:
def normed_timing_matrix(Mmat):
    """
    Normalize the timing design matrix
    """
    norm = np.sqrt(np.sum(Mmat ** 2, axis=0))
    nmat = Mmat / norm
    nmat[:, norm == 0] = 0

    return nmat

In [83]:
normed_timing_matrix(psrs[0].Mmat)

array([[ 0.01334164, -0.00607742, -0.01744352, ...,  0.        ,
         0.        , -0.01498558],
       [ 0.01334164, -0.00607742, -0.01744352, ...,  0.        ,
         0.        , -0.01498558],
       [ 0.01334164, -0.00607742, -0.01744352, ...,  0.        ,
         0.        , -0.01498558],
       ...,
       [ 0.01334164, -0.00633331, -0.01738768, ...,  0.        ,
         0.24175482,  0.        ],
       [ 0.01334164, -0.00633331, -0.01738768, ...,  0.        ,
         0.24519369,  0.        ],
       [ 0.01334164, -0.00633331, -0.01738768, ...,  0.        ,
         0.24346461,  0.        ]])

In [28]:
pta0.get_phi([0, -20, -20])

array([[1.61615689e-15, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.61615689e-15, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.54318744e-17, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+40, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+40, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+40]])

In [226]:
loglikelihood([0, -20, -20])

[-1.92338291e+08 -1.92006190e+08 -3.56734832e+08  8.37862637e+07
 -3.87585587e+07  3.45236522e+08  5.71308814e+08  2.52851049e+08
  5.71837765e+08 -7.82235369e+08 -6.03129254e+08 -6.80115418e+08
 -6.25073555e+08  2.84605646e+08 -3.60896263e+07  5.08763355e+08
  4.61669541e+08  1.12117650e+08  5.53619861e+07 -2.52947282e+08
 -7.68350547e+05 -1.06875552e+06  6.84861398e+07 -6.21657436e+07
 -1.34877036e+07 -2.47768968e+07 -6.31760535e+07  1.19596863e+08
  3.56080708e+08  2.00148536e+08  2.76986313e+08 -4.27755791e+08
 -3.76929911e+08 -2.96632475e+08 -2.12297550e+08  1.35335929e+08
  9.98871823e+07  1.73572735e+08  1.83507026e+08 -1.36686007e+08
 -8.86374206e+07 -8.46351658e+07  4.35739567e+07  7.25782490e+07
 -3.35063655e+07 -8.26670733e+07 -1.31957029e+08 -3.40125942e+07
  5.36453643e+07  1.00726093e+08  2.30957098e+08 -3.19347401e+07
 -1.96226619e+07 -2.23097627e+08 -1.24567390e+08 -5.71725483e+07
 -6.36532071e+07  1.32643614e+07  3.09559775e+07  3.37785429e+07]


66800.95160624692

In [220]:
pta0._signalcollections[0].get_FDr()

array([-1.92338291e+08, -1.92006190e+08, -3.56734832e+08,  8.37862637e+07,
       -3.87585587e+07,  3.45236522e+08,  5.71308814e+08,  2.52851049e+08,
        5.71837765e+08, -7.82235369e+08, -6.03129254e+08, -6.80115418e+08,
       -6.25073555e+08,  2.84605646e+08, -3.60896263e+07,  5.08763355e+08,
        4.61669541e+08,  1.12117650e+08,  5.53619861e+07, -2.52947282e+08,
       -7.68350557e+05, -1.06875552e+06,  6.84861398e+07, -6.21657436e+07,
       -1.34877036e+07, -2.47768968e+07, -6.31760535e+07,  1.19596863e+08,
        3.56080708e+08,  2.00148536e+08,  2.76986313e+08, -4.27755791e+08,
       -3.76929911e+08, -2.96632475e+08, -2.12297550e+08,  1.35335929e+08,
        9.98871823e+07,  1.73572735e+08,  1.83507026e+08, -1.36686007e+08,
       -8.86374206e+07, -8.46351658e+07,  4.35739567e+07,  7.25782490e+07,
       -3.35063655e+07, -8.26670733e+07, -1.31957029e+08, -3.40125942e+07,
        5.36453643e+07,  1.00726093e+08,  2.30957098e+08, -3.19347401e+07,
       -1.96226619e+07, -

In [151]:
N = pta.get_ndiag()
N_inv = [np.diag(N**(-1)) for N in N][0]
Mmat = [utils.normed_tm_basis(psrs[ii].Mmat)[0] for ii in range(len(psrs))][0]
r = pta.get_residuals()[0]

# T = F when timing model isn't included (so don't include it!)
F = pta.get_basis(pta.params)[0]

In [158]:
# FNF good:
np.allclose(pta0._signalcollections[0].get_FNF(), np.matmul(F.T, np.matmul(N_inv, F)))

True

In [163]:
np.allclose(pta0._signalcollections[0].get_MNF(), np.matmul(Mmat.T, np.matmul(N_inv, F)))

True

In [170]:
A = np.matmul(Mmat.T, np.matmul(N_inv, F))
S = np.matmul(Mmat.T, np.matmul(N_inv, Mmat))
cf = np.linalg.cholesky(S)
c = np.linalg.solve(cf, np.identity(S.shape[0]))
S_inv = np.dot(c.T, c)

In [175]:
np.allclose(np.matmul(S_inv, A), pta0._signalcollections[0].get_MNMMNF())

True

In [200]:
pta0._signalcollections[0].get_FNF()

array([[ 1.00548511e+16,  1.18221312e+15,  1.28795599e+15, ...,
         1.40819227e+15,  1.71772130e+14, -1.64457469e+15],
       [ 1.18221312e+15,  1.12466783e+16,  6.45946679e+15, ...,
        -4.83478605e+14,  2.32039972e+14,  1.60750562e+15],
       [ 1.28795599e+15,  6.45946679e+15,  8.90025537e+15, ...,
        -1.14480056e+15, -2.15423342e+14,  2.76667160e+15],
       ...,
       [ 1.40819227e+15, -4.83478605e+14, -1.14480056e+15, ...,
         1.08893387e+16,  3.28933675e+15,  4.93498094e+15],
       [ 1.71772130e+14,  2.32039972e+14, -2.15423342e+14, ...,
         3.28933675e+15,  6.99313956e+15,  5.28877459e+14],
       [-1.64457469e+15,  1.60750562e+15,  2.76667160e+15, ...,
         4.93498094e+15,  5.28877459e+14,  1.43083899e+16]])

In [209]:
FNF = pta0._signalcollections[0].get_FNF()
MNF = pta0._signalcollections[0].get_MNF()
MNMMNF = pta0._signalcollections[0].get_MNMMNF()

In [208]:
np.allclose(pta0._signalcollections[0].get_basis_F(), F)

True

In [211]:
np.matmul(MNF.T, MNMMNF)

array([[ 9.77547320e+15,  9.16991876e+14,  9.01477298e+14, ...,
         1.41468220e+15,  1.11052380e+14, -1.67129894e+15],
       [ 9.16991876e+14,  1.05384120e+16,  6.22779603e+15, ...,
        -5.17688776e+14,  4.56553143e+13,  1.68311534e+15],
       [ 9.01477298e+14,  6.22779603e+15,  7.66726841e+15, ...,
        -1.21523150e+15, -1.01210748e+14,  2.73527040e+15],
       ...,
       [ 1.41468220e+15, -5.17688776e+14, -1.21523150e+15, ...,
         7.73841112e+15,  1.71272298e+15,  3.95409932e+15],
       [ 1.11052380e+14,  4.56553143e+13, -1.01210748e+14, ...,
         1.71272298e+15,  4.31932439e+15,  4.63459729e+14],
       [-1.67129894e+15,  1.68311534e+15,  2.73527040e+15, ...,
         3.95409932e+15,  4.63459729e+14,  1.08421130e+16]])

In [214]:
pta0._signalcollections[0].get_FDF()

array([[ 1.98303243e+16,  2.09920500e+15,  2.18943329e+15, ...,
         2.82287447e+15,  2.82824510e+14, -3.31587363e+15],
       [ 2.09920500e+15,  2.17850902e+16,  1.26872628e+16, ...,
        -1.00116738e+15,  2.77695286e+14,  3.29062096e+15],
       [ 2.18943329e+15,  1.26872628e+16,  1.65675238e+16, ...,
        -2.36003206e+15, -3.16634089e+14,  5.50194200e+15],
       ...,
       [ 2.82287447e+15, -1.00116738e+15, -2.36003206e+15, ...,
         1.86277498e+16,  5.00205973e+15,  8.88908026e+15],
       [ 2.82824510e+14,  2.77695286e+14, -3.16634089e+14, ...,
         5.00205973e+15,  1.13124639e+16,  9.92337187e+14],
       [-3.31587363e+15,  3.29062096e+15,  5.50194200e+15, ...,
         8.88908026e+15,  9.92337187e+14,  2.51505029e+16]])

In [237]:
like = FastLikelihood(pta0)

Loading fastloglikelihood version of signal_base


In [238]:
like.lnlikelihood

66800.95160614939