In [116]:
from sample_psrs import load_psrs, fake_model_2a, fake_model_2a_no_tm
from pta_fast_model import FastLogLikelihood
from enterprise.signals.signal_base import FastLogLikelihood as FastLikelihood

import numpy as np

from enterprise.signals import utils
from enterprise_extensions.models import model_2a
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [66]:
psrs = load_psrs(1e-15, 1)

In [117]:
# pta0 = fake_model_2a(psrs)
# pta0 = model_3a(psrs, gamma_common=13/3)
pta0 = model_2a(psrs, gamma_common=13/3)

No noise dictionary provided!...


In [118]:
pta0.get_lnlikelihood([0, 0, -20, -20, -20])

TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'int'

In [115]:
pta0.get_lnlikelihood([0, 0, -20, -20, -20])

51036.67147527122

In [225]:
pta = fake_model_2a_no_tm([psrs[0]])

In [217]:
loglikelihood = FastLogLikelihood(pta, [psrs[0]])

In [221]:
loglikelihood([0, -20, -20])

[[ 2.79377943e+14  2.65221247e+14  3.86478693e+14 ... -6.48993356e+12
   6.07197497e+13  2.67242472e+13]
 [ 2.65221247e+14  7.08266327e+14  2.31670766e+14 ...  3.42101711e+13
   1.86384658e+14 -7.56097235e+13]
 [ 3.86478693e+14  2.31670766e+14  1.23298697e+15 ...  7.04309407e+13
  -1.14212594e+14  3.14011952e+13]
 ...
 [-6.48993360e+12  3.42101710e+13  7.04309406e+13 ...  3.15092756e+15
   1.57661377e+15  9.80881622e+14]
 [ 6.07197496e+13  1.86384658e+14 -1.14212594e+14 ...  1.57661377e+15
   2.67381517e+15  6.54177302e+13]
 [ 2.67242473e+13 -7.56097235e+13  3.14011952e+13 ...  9.80881622e+14
   6.54177302e+13  3.46627684e+15]]


66800.95160624692

In [26]:
pta0._signalcollections[1].get_phi([0, -20, -20]).shape

(241,)

In [28]:
pta0.get_phi([0, -20, -20])

array([[1.61615689e-15, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.61615689e-15, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.54318744e-17, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+40, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+40, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+40]])

In [226]:
loglikelihood([0, -20, -20])

[-1.92338291e+08 -1.92006190e+08 -3.56734832e+08  8.37862637e+07
 -3.87585587e+07  3.45236522e+08  5.71308814e+08  2.52851049e+08
  5.71837765e+08 -7.82235369e+08 -6.03129254e+08 -6.80115418e+08
 -6.25073555e+08  2.84605646e+08 -3.60896263e+07  5.08763355e+08
  4.61669541e+08  1.12117650e+08  5.53619861e+07 -2.52947282e+08
 -7.68350547e+05 -1.06875552e+06  6.84861398e+07 -6.21657436e+07
 -1.34877036e+07 -2.47768968e+07 -6.31760535e+07  1.19596863e+08
  3.56080708e+08  2.00148536e+08  2.76986313e+08 -4.27755791e+08
 -3.76929911e+08 -2.96632475e+08 -2.12297550e+08  1.35335929e+08
  9.98871823e+07  1.73572735e+08  1.83507026e+08 -1.36686007e+08
 -8.86374206e+07 -8.46351658e+07  4.35739567e+07  7.25782490e+07
 -3.35063655e+07 -8.26670733e+07 -1.31957029e+08 -3.40125942e+07
  5.36453643e+07  1.00726093e+08  2.30957098e+08 -3.19347401e+07
 -1.96226619e+07 -2.23097627e+08 -1.24567390e+08 -5.71725483e+07
 -6.36532071e+07  1.32643614e+07  3.09559775e+07  3.37785429e+07]


66800.95160624692

In [220]:
pta0._signalcollections[0].get_FDr()

array([-1.92338291e+08, -1.92006190e+08, -3.56734832e+08,  8.37862637e+07,
       -3.87585587e+07,  3.45236522e+08,  5.71308814e+08,  2.52851049e+08,
        5.71837765e+08, -7.82235369e+08, -6.03129254e+08, -6.80115418e+08,
       -6.25073555e+08,  2.84605646e+08, -3.60896263e+07,  5.08763355e+08,
        4.61669541e+08,  1.12117650e+08,  5.53619861e+07, -2.52947282e+08,
       -7.68350557e+05, -1.06875552e+06,  6.84861398e+07, -6.21657436e+07,
       -1.34877036e+07, -2.47768968e+07, -6.31760535e+07,  1.19596863e+08,
        3.56080708e+08,  2.00148536e+08,  2.76986313e+08, -4.27755791e+08,
       -3.76929911e+08, -2.96632475e+08, -2.12297550e+08,  1.35335929e+08,
        9.98871823e+07,  1.73572735e+08,  1.83507026e+08, -1.36686007e+08,
       -8.86374206e+07, -8.46351658e+07,  4.35739567e+07,  7.25782490e+07,
       -3.35063655e+07, -8.26670733e+07, -1.31957029e+08, -3.40125942e+07,
        5.36453643e+07,  1.00726093e+08,  2.30957098e+08, -3.19347401e+07,
       -1.96226619e+07, -

In [151]:
N = pta.get_ndiag()
N_inv = [np.diag(N**(-1)) for N in N][0]
Mmat = [utils.normed_tm_basis(psrs[ii].Mmat)[0] for ii in range(len(psrs))][0]
r = pta.get_residuals()[0]

# T = F when timing model isn't included (so don't include it!)
F = pta.get_basis(pta.params)[0]

In [158]:
# FNF good:
np.allclose(pta0._signalcollections[0].get_FNF(), np.matmul(F.T, np.matmul(N_inv, F)))

True

In [163]:
np.allclose(pta0._signalcollections[0].get_MNF(), np.matmul(Mmat.T, np.matmul(N_inv, F)))

True

In [170]:
A = np.matmul(Mmat.T, np.matmul(N_inv, F))
S = np.matmul(Mmat.T, np.matmul(N_inv, Mmat))
cf = np.linalg.cholesky(S)
c = np.linalg.solve(cf, np.identity(S.shape[0]))
S_inv = np.dot(c.T, c)

In [175]:
np.allclose(np.matmul(S_inv, A), pta0._signalcollections[0].get_MNMMNF())

True

In [200]:
pta0._signalcollections[0].get_FNF()

array([[ 1.00548511e+16,  1.18221312e+15,  1.28795599e+15, ...,
         1.40819227e+15,  1.71772130e+14, -1.64457469e+15],
       [ 1.18221312e+15,  1.12466783e+16,  6.45946679e+15, ...,
        -4.83478605e+14,  2.32039972e+14,  1.60750562e+15],
       [ 1.28795599e+15,  6.45946679e+15,  8.90025537e+15, ...,
        -1.14480056e+15, -2.15423342e+14,  2.76667160e+15],
       ...,
       [ 1.40819227e+15, -4.83478605e+14, -1.14480056e+15, ...,
         1.08893387e+16,  3.28933675e+15,  4.93498094e+15],
       [ 1.71772130e+14,  2.32039972e+14, -2.15423342e+14, ...,
         3.28933675e+15,  6.99313956e+15,  5.28877459e+14],
       [-1.64457469e+15,  1.60750562e+15,  2.76667160e+15, ...,
         4.93498094e+15,  5.28877459e+14,  1.43083899e+16]])

In [209]:
FNF = pta0._signalcollections[0].get_FNF()
MNF = pta0._signalcollections[0].get_MNF()
MNMMNF = pta0._signalcollections[0].get_MNMMNF()

In [208]:
np.allclose(pta0._signalcollections[0].get_basis_F(), F)

True

In [211]:
np.matmul(MNF.T, MNMMNF)

array([[ 9.77547320e+15,  9.16991876e+14,  9.01477298e+14, ...,
         1.41468220e+15,  1.11052380e+14, -1.67129894e+15],
       [ 9.16991876e+14,  1.05384120e+16,  6.22779603e+15, ...,
        -5.17688776e+14,  4.56553143e+13,  1.68311534e+15],
       [ 9.01477298e+14,  6.22779603e+15,  7.66726841e+15, ...,
        -1.21523150e+15, -1.01210748e+14,  2.73527040e+15],
       ...,
       [ 1.41468220e+15, -5.17688776e+14, -1.21523150e+15, ...,
         7.73841112e+15,  1.71272298e+15,  3.95409932e+15],
       [ 1.11052380e+14,  4.56553143e+13, -1.01210748e+14, ...,
         1.71272298e+15,  4.31932439e+15,  4.63459729e+14],
       [-1.67129894e+15,  1.68311534e+15,  2.73527040e+15, ...,
         3.95409932e+15,  4.63459729e+14,  1.08421130e+16]])

In [214]:
pta0._signalcollections[0].get_FDF()

array([[ 1.98303243e+16,  2.09920500e+15,  2.18943329e+15, ...,
         2.82287447e+15,  2.82824510e+14, -3.31587363e+15],
       [ 2.09920500e+15,  2.17850902e+16,  1.26872628e+16, ...,
        -1.00116738e+15,  2.77695286e+14,  3.29062096e+15],
       [ 2.18943329e+15,  1.26872628e+16,  1.65675238e+16, ...,
        -2.36003206e+15, -3.16634089e+14,  5.50194200e+15],
       ...,
       [ 2.82287447e+15, -1.00116738e+15, -2.36003206e+15, ...,
         1.86277498e+16,  5.00205973e+15,  8.88908026e+15],
       [ 2.82824510e+14,  2.77695286e+14, -3.16634089e+14, ...,
         5.00205973e+15,  1.13124639e+16,  9.92337187e+14],
       [-3.31587363e+15,  3.29062096e+15,  5.50194200e+15, ...,
         8.88908026e+15,  9.92337187e+14,  2.51505029e+16]])

In [237]:
like = FastLikelihood(pta0)

Loading fastloglikelihood version of signal_base


In [238]:
like.lnlikelihood

66800.95160614939